pre-commit:
  parallel: true
  jobs:
    - name: editorconfig-checker
      run: uv run ec
    - name: Typos
      run: uv run typos
    - group:
        parallel: true
        jobs:
          - name: Ruff Check
            run: uv run ruff check
          - name: Ruff Format
            run: uv run ruff format --check
    - name: ty
      run: uv run ty check
    - name: sphinx-lint
      run: uv run task docs-lint

commit-msg:
  jobs:
    - name: Commitlint
      run: commitlint --file=./.git/COMMIT_EDITMSG

check:
  parallel: true
  jobs:
    - name: editorconfig-checker
      run: uv run ec
    - name: Typos
      run: uv run typos
    - group:
        parallel: true
        jobs:
          - name: Ruff Check
            run: uv run ruff check
          - name: Ruff Format
            run: uv run ruff format --check
    - name: ty
      run: uv run ty check
    - name: sphinx-lint
      run: uv run task docs-lint

fix:
  jobs:
    - name: editorconfig-checker
      run: uv run ec
    - name: Typos
      run: uv run typos -w
    - group:
        jobs:
          - name: Ruff Check
            run: uv run ruff check --fix
          - name: Ruff Format
            run: uv run ruff format
    - name: ty
      run: uv run ty check
    - name: sphinx-lint
      run: uv run task docs-lint
