[build-system]
requires = ["setuptools == 75.8.0", "setuptools_scm == 8.2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "objctypes"
dynamic = ["version"]
requires-python = ">= 3.13"
authors = [
  { name = "qqfunc", email = "148628110+qqfunc@users.noreply.github.com" },
]
maintainers = [
  { name = "qqfunc", email = "148628110+qqfunc@users.noreply.github.com" },
]
description = "Use Objective-C features in Python"
readme = "README.md"
license = { file = "LICENSE.md" }
keywords = ["objctypes", "objc", "Objective-C", "ObjectiveC"]
classifiers = [
  "Development Status :: 1 - Planning",
  "Environment :: MacOS X :: Cocoa",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: The Unlicense (Unlicense)",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: iOS",
  "Programming Language :: Objective C",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Typing :: Typed",
]

[project.urls]
Repository = "https://github.com/qqfunc/objctypes"
Issues = "https://github.com/qqfunc/objctypes/issues"

[dependency-groups]
check = [
  "mypy == 1.15.0",
  "pytest == 8.3.4",
  "pytest-xdist == 3.6.1",
  "ruff ==0.9.7",
  "types-setuptools == 75.8.0.20250210",
]
gh-actions = [
  { include-group = "check" },
  "pytest-github-actions-annotate-failures == 0.3.0",
]
dev = [{ include-group = "check" }, "editorconfig-checker == 3.2.0"]
docs = [
  "furo == 2024.8.6",
  "readthedocs-sphinx-search == 0.3.2",
  "sphinx == 8.1.3",
  "sphinx-autobuild == 2024.10.3",
  "sphinx-copybutton == 0.5.2",
  "sphinx-hoverxref == 1.4.1",
  "sphinx-notfound-page == 1.0.4",
]

[tool.mypy]
exclude = ["^build/"]

[tool.pytest.ini_options]
addopts = "-n auto"

[tool.ruff]
line-length = 79

[tool.ruff.format]
docstring-code-line-length = 72

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D203", # one-blank-line-before-class
  "D213", # multi-line-summary-second-line
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 72

[tool.ruff.lint.per-file-ignores]
"setup.py" = [
  "S603", # subprocess-without-shell-equals-true
]
"docs/conf.py" = [
  "INP001", # implicit-namespace-package
]
"tests/**.py" = [
  "S101",    # assert
  "INP001",  # implicit-namespace-package
  "PLR2004", # magic-value-comparison
]

[tool.setuptools_scm]
