name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13', '3.14']
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v5.0.0
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6.0.0
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install uv
      uses: astral-sh/setup-uv@v7.1.0
      with:
        enable-cache: true
    - name: Install libffi
      run: brew install libffi
    - name: Install dependencies
      run: uv sync --group gh-actions-build --no-default-groups
    - name: Test with pytest
      run: uv run --no-default-groups pytest
    - name: Prune uv cache
      run: uv cache prune --ci

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v5.0.0
    - name: Install uv
      uses: astral-sh/setup-uv@v7.1.0
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync --group gh-actions-check --no-default-groups
    - name: Check files with editorconfig-checker
      run: uv run --no-default-groups ec -format github-actions -no-color
    - name: Spell check with typos
      run: uv run --no-default-groups typos
    - name: Check with Ruff
      run: uv run --no-default-groups ruff check --output-format=github
    - name: Format with Ruff
      run: uv run --no-default-groups ruff format --check --preview --output-format=github
    - name: Type Check with ty
      run: uv run --no-default-groups ty check --output-format=github
    - name: Prune uv cache
      run: uv cache prune --ci
