name: Check

on:
  push:
    branches: [main]
    paths: ['**/.editorconfig']
  pull_request:
    branches: [main]
    paths: ['**/.editorconfig']

env:
  FORCE_COLOR: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check EditorConfig
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-suffix: check
    - name: Install dependencies
      run: uv sync --group check-editorconfig --no-default-groups --no-install-workspace
    - name: Check with editorconfig-checker
      run: uv run ec -format github-actions
